name: Do Something That Needs Scheduled
on:
  repository_dispatch:
    types: new-bm
jobs:
  build:
    name: Run Some Scheduled Thing
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: Do Something Based On Triggered Event Data
        run: 'echo "Triggered event text: ${{ github.event.client_payload.data }}"'

      - name: Trigger bookmark
        uses: ./.github/actions
        with:
          mndata: "${{github.event.client_payload.data}}"

      - name: add commit and push
        run: |
          git add .
          git commit -m "update data file"
          git push
