name: Update Bookmarks
on:
  repository_dispatch:
    types: new-bm
jobs:
  build:
    name: Run Some Scheduled Thing
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: save date input
        run: |
          str='${{ toJson(github.event.client_payload.data) }}'
          echo "$str" > ./datafile.txt
          echo $(sed -e ':a' -e 'N' -e '$!ba' -e 's/\n/ /g' datafile.txt ) > datafile.txt

      - name: Update JSON data
        run: |
          npm install
          npm run build:repo
          npm run release:repo
