name: Do Something That Needs Scheduled
on:
  repository_dispatch:
    types: new-bm
jobs:
  build:
    name: Run Some Scheduled Thing
    runs-on: ubuntu-latest
    steps:
      - name: Do Something
        run: echo Doing Something...

      - name: Do Something Based On Triggered Event Data
        run: 'echo "Triggered event text: ${{ github.event.client_payload.text }}"'

      - name: checkout
        uses: actions/checkout@v2

      - name: Trigger bookmark
        uses: ./.github/actions
        with:
          mndata: ${{github.event.client_payload}}
