name: BookieBot
on:
  repository_dispatch:
    types: new-bm
jobs:
  build:
    name: Run Some Scheduled Thing
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: save dat input
        run: |
          echo ${{ toJson(github.event.client_payload.data) }} > .datafile

      - name: release
        run: |
          npm install
          npm run build:repo
          npm run push:repo
          npm run build:ui
          npm run push:ui
