name: BookieBot
on:
  repository_dispatch:
    types: new-bm
jobs:
  build:
    name: Run Some Scheduled Thing
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: testing..
        run: |
          echo "${{ github.event.client_payload.data }}"
          echo "${{ toJson(github.event.client_payload.data) }}"

      - name: release
        run: |
          npm install
          npm run build:repo -- ${{ toJson(github.event.client_payload.data) }}
          npm run push:repo
          npm run build:ui
          npm run push:ui
