name: Build UI
on: push
jobs:
  build:
    name: Build application on push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build UI
        run: |
          npm install
          npm run build:ui

      - name: Deploy UI
        uses: peaceiris/actions-gh-pages@v2
        env:
          GITHUB_TOKEN: ${{ secrets.BM_GITHUB_TOKEN }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: ./public
